version: "3.9"

services:
  
  api:
    image: patna/api
    restart: always
    environment:
      DATABASE_URL: "host=postgresql user=peagolang password=supersecret dbname=peagolang sslmode=disable"
    ports:
      - "8624:8624"
    depends_on:
      - postgresql
    networks:
      - pattana

  postgresql:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=peagolang
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=peagolang
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "8625:5432"
    networks:
      - pattana

networks:
  pattana:
    name: pattana

