version: "3.9"

services:
  
  api:
    image: patna/api:latest
    restart: always
    environment:
      DATABASE_URL: "host=postgresql user=patnagolang password=supersecretpatnagolang dbname=patnapostgresqldb sslmode=disable"
    ports:
      - "8624:8624"
    depends_on:
      - postgresql
    networks:
      - pattana

  postgresql:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=patnagolang
      - POSTGRES_PASSWORD=supersecretpatnagolang
      - POSTGRES_DB=patnapostgresqldb
    volumes:
      - ./data/postgres:/var/lib/postgresql/patna/data
    ports:
      - "8625:5432"
    networks:
      - pattana

networks:
  pattana:
    name: pattana

